#! /bin/bash

if [ ! -e $DPATH/setting ]
then
	touch $DPATH/setting
	echo "# you can edit this file to change the initely task" >> $DPATH/setting
	echo "# format just like : "number.the task you want to add"" >> $DPATH/setting
	echo "# save it after you changing just ok" >> $DPATH/setting
	echo "" >> $DPATH/setting
	echo "# example :" >> $DPATH/setting
	echo "# 1.this is the first task you need to finish" >> $DPATH/setting
fi

dtodayday=`date '+%d'`
dtodaymon=`date '+%b'`
dtodayear=`date '+%Y'`

cat $DPATH/setting | while read line
do
	if [[ ${line:0:1} = [0-9] ]]
	then
		read tmp < $DPATH/uesr/dday/all/"$dtodayday-$dtodaymon-$dtodayear"
		tmp=$[ $tmp + 1 ]
		echo $tmp > $DPATH/uesr/dday/all/"$dtodayday-$dtodaymon-$dtodayear"

		read tmp < $DPATH/uesr/dmonth/all/"$dtodaymon-$dtodayear"
		tmp=$[ $tmp + 1 ]
		echo $tmp > $DPATH/uesr/dmonth/all/"$dtodaymon-$dtodayear"

		read tmp < $DPATH/uesr/dyear/all/"$dtodayear"
		tmp=$[ $tmp + 1 ]
		echo $tmp > $DPATH/uesr/dyear/all/"$dtodayear"

		echo $line >> $DPATH/task/"$dtodayday-$dtodaymon-$dtodayear"
	fi

done

