#! /bin/bash

echo "please input your new task:"

read str
task="0."
task=$task$str

dtodayday=`date '+%d'`
dtodaymon=`date '+%b'`
dtodayear=`date '+%Y'`

echo $task >> $DPATH/task/"$dtodayday-$dtodaymon-$dtodayear"
$DPATH/bin/Sortfile $DPATH/task/"$dtodayday-$dtodaymon-$dtodayear"

read num < $DPATH/uesr/dday/all/"$dtodayday-$dtodaymon-$dtodayear"
num=$[ $num + 1 ]
echo $num > $DPATH/uesr/dday/all/"$dtodayday-$dtodaymon-$dtodayear"

read num < $DPATH/uesr/dmonth/all/"$dtodaymon-$dtodayear"
num=$[ $num + 1 ]
echo $num > $DPATH/uesr/dmonth/all/"$dtodaymon-$dtodayear"

read num < $DPATH/uesr/dyear/all/"$dtodayear"
num=$[ $num + 1 ]
echo $num > $DPATH/uesr/dyear/all/"$dtodayear"

dtoday
