#! /bin/bash

echo "input your password please : "

read str

if [ $str = "woshizyh" ]
then
	rm $DPATH/uesr/dday/all/*
	rm $DPATH/uesr/dday/finish/*
	echo "" > $DPATH/uesr/dday/log

	rm $DPATH/uesr/dmonth/all/*
	rm $DPATH/uesr/dmonth/finish/*
	echo "" > $DPATH/uesr/dmonth/log
	
	rm $DPATH/uesr/dyear/all/*
	rm $DPATH/uesr/dyear/finish/*
	echo "" > $DPATH/uesr/dyear/log

	rm $DPATH/task/*
else
	echo "wrong password !"
fi
