#! /bin/bash
export DPATH

if [ ! -e $DPATH/uesr/log ]
then
	touch $DPATH/uesr/log
	echo "[`date`]:create this new log file" > $DPATH/uesr/log
fi

dtodayday=`date '+%d'`
dtodaymon=`date '+%b'`
dtodayear=`date '+%Y'`

if [ -e $DPATH/task/"$dtodayday-$dtodaymon-$dtodayear" ]
then
	echo "there have exist today's task file !"
	exit
fi

if [ ! -e $DPATH/uesr/dday/all/"$dtodayday-$dtodaymon-$dtodayear" ]
then
	echo "$dtodayday-$dtodaymon-$dtodayear" >> $DPATH/uesr/dday/log
	touch $DPATH/uesr/dday/all/"$dtodayday-$dtodaymon-$dtodayear"
	echo "0" > $DPATH/uesr/dday/all/"$dtodayday-$dtodaymon-$dtodayear"
	touch $DPATH/uesr/dday/finish/"$dtodayday-$dtodaymon-$dtodayear"
	echo "0" > $DPATH/uesr/dday/finish/"$dtodayday-$dtodaymon-$dtodayear"
fi

if [ ! -e $DPATH/uesr/dmonth/all/"$dtodaymon-$dtodayear" ]
then
	echo "$dtodaymon-$dtodayear" >> $DPATH/uesr/dmonth/log
	touch $DPATH/uesr/dmonth/all/"$dtodaymon-$dtodayear"
	echo "0" > $DPATH/uesr/dmonth/all/"$dtodaymon-$dtodayear"
	touch $DPATH/uesr/dmonth/finish/"$dtodaymon-$dtodayear"
	echo "0" > $DPATH/uesr/dmonth/finish/"$dtodaymon-$dtodayear"
fi

if [ ! -e $DPATH/uesr/dyear/all/"$dtodayear" ]
then
	echo "$dtodayear" >> $DPATH/uesr/dyear/log
	touch $DPATH/uesr/dyear/all/"$dtodayear"
	echo "0" > $DPATH/uesr/dyear/all/"$dtodayear"
	touch $DPATH/uesr/dyear/finish/"$dtodayear"
	echo "0" > $DPATH/uesr/dyear/finish/"$dtodayear"
fi

touch $DPATH/task/"$dtodayday-$dtodaymon-$dtodayear"
$DPATH/uesr/initask $DPATH/task/"$dtodayday-$dtodaymon-$dtodayear"

echo "[`date`]:update to a new day's task" >> $DPATH/uesr/log

